### ISSUE TITLE
Question to Mezz!

### ISSUE THREAD

**Issue by xMrVizzy** [xMrVizzy/Faithful#1]

**Comment by xMrVizzy** [comment]
@mezz
@mezz

**Comment by xMrVizzy** [comment]
@mezz i have a Question with Curseforge API, Is it possible to autobuild and uploade pack on Curse like mods? And can you help me with it, please)

**Comment by mezz** [comment]
I use this plugin for gradle to upload to Curse: https://github.com/matthewprenger/CurseGradle
I don't know the answer to your question, but you should be able to find everything you need there, as well as support.

**Comment by xMrVizzy** [comment]
Okay, I too use this plugin for my mods.
